# Hospital Readmissions Data Analysis and Recommendations for Reduction

### Appendix A. Wilcoxon test for the red region

In [68]:
#read csv
df<-read.csv('data/cms_hospital_readmissions.csv')
head(df,3)

Hospital.Name                        Provider.Number State
1 FROEDTERT MEMORIAL LUTHERAN HOSPITAL 520177          WI   
2 PROVIDENCE HOSPITAL                   90006          DC   
3 BEAUFORT COUNTY MEMORIAL HOSPITAL    420067          SC   
  Measure.Name           Number.of.Discharges Footnote Excess.Readmission.Ratio
1 READM-30-HIP-KNEE-HRRP 242                  NA       1.9095                  
2 READM-30-HIP-KNEE-HRRP 247                  NA       1.7521                  
3 READM-30-HIP-KNEE-HRRP 586                  NA       1.5836                  
  Predicted.Readmission.Rate Expected.Readmission.Rate Number.of.Readmissions
1 10.8                       5.6                       38                    
2  9.2                       5.3                       33                    
3  7.6                       4.8                       53                    
  Start.Date End.Date  
1 07/01/2010 06/30/2013
2 07/01/2010 06/30/2013
3 07/01/2010 06/30/2013

In [69]:
df_y<-df$Excess.Readmission.Ratio[81:16857] #set column
head(df_y,3)

[1] 1.3104 1.3099 1.3058

In [70]:
df_y_red<-df_y[(df_y>=1.15)&(df_y<=2)] #prepare data
head(df_y_red,20)

[1] 1.3104 1.3099 1.3058 1.3038 1.3020 1.3012 1.3008 1.2999 1.2987 1.2971
[11] 1.2963 1.2949 1.2941 1.2939 1.2915 1.2909 1.2871 1.2865 1.2863 1.2858

In [71]:
#perform Wilcoxon one sample test
wilcox.test(df_y_red,mu=1.0, alternative="greater")


	Wilcoxon signed rank test with continuity correction

data:  df_y_red
V = 187580, p-value < 2.2e-16
alternative hypothesis: true location is greater than 1


- At alpha=0.01, the Wilcoxon test rejects the null hypothesis (i.e., the median of the sample is greater than 1.0)

In [72]:
wilcox.test(df_y_red,mu=1.0)


	Wilcoxon signed rank test with continuity correction

data:  df_y_red
V = 187580, p-value < 2.2e-16
alternative hypothesis: true location is not equal to 1


### Appendix B. Wilcoxon test for the green region

In [73]:
df_y_green<-df_y[(df_y>=0.5)&(df_y<=0.95)] #prepare data
head(df_y_green,3) #check

[1] 0.95 0.95 0.95

In [74]:
#perform Wilcoxon one sample test
wilcox.test(df_y_green,mu=1.0, alternative="less")


	Wilcoxon signed rank test with continuity correction

data:  df_y_green
V = 0, p-value < 2.2e-16
alternative hypothesis: true location is less than 1


- Atalpha=0.01, the Wilcoxon test rejects the null hypothesis (i.e., the median of the sample is less than 1.0)

### Appendix C. Compare the medians between the two independent distributions

In [75]:
wilcox.test(df_y_red,df_y_green,alternative="two.sided")


	Wilcoxon rank sum test with continuity correction

data:  df_y_red and df_y_green
W = 2121200, p-value < 2.2e-16
alternative hypothesis: true location shift is not equal to 0


- At alpha=0.01, the Wilcoxon test concludes that the medians of the two distributions are not equal.

### Appendix D. Wilcoxon test to compare the means for number of discharges less than 100

In [106]:
df_xy_lt_100<-read.csv('data/df_xy_lt_100.csv') #load data for hospitals with number of disharges <100
head(df_xy_lt_100,3) #check

#perform a Wilcoxon test
wilcox.test(df_xy_lt_100$y,mu=1.023,alternative="two.sided",conf.level=0.99)

x  y     
1 25 1.0914
2 27 1.0961
3 28 1.0934


	Wilcoxon signed rank test with continuity correction

data:  df_xy_lt_100$y
V = 319960, p-value = 0.005823
alternative hypothesis: true location is not equal to 1.023


- At alpha=0.01, the Wilcoxon test rejects the null hypothesis (i.e., the excess readmission rate is not equal to 1.023).

### Appendix E. Wilcoxon test to compare the means for number of discharges greater than 1000

In [107]:
df_xy_gt_1000<-read.csv('data/df_xy_gt_1000.csv') #load data for hospitals with number of disharges >1000
head(df_xy_gt_1000,3) #check

#perform a Wilcoxon test
wilcox.test(df_xy_gt_1000$y,mu=0.978,alternative="two.sided")

x    y     
1 1002 0.9192
2 1004 1.1405
3 1007 1.0760


	Wilcoxon signed rank test with continuity correction

data:  df_xy_gt_1000$y
V = 55600, p-value = 0.3223
alternative hypothesis: true location is not equal to 0.978


- At alpha=0.01, the Wilcoxon test fails to reject the null hypothesis (i.e., the excess readmission rate is equal to 0.978).

### Appendix F. Wilcoxon test to compare the means for number of discharges less than 300

In [111]:
df_xy_lt_300<-read.csv('data/df_xy_lt_300.csv') #load data for hospitals with number of disharges <300

head(df_xy_lt_300,3) #check

#perform a Wilcoxon test
wilcox.test(df_xy_gt_1000$y,mu=1,alternative="greater")

x  y     
1 25 1.0914
2 27 1.0961
3 28 1.0934


	Wilcoxon signed rank test with continuity correction

data:  df_xy_gt_1000$y
V = 43847, p-value = 0.9993
alternative hypothesis: true location is greater than 1


- At alpha=0.01, the Wilcoxon test rejects the null hypothesis (i.e., the excess readmission rate is greater than 1).